/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangePassword: typeof import('./components/Props/ChangePassword/index.vue')['default']
    IconAdd: typeof import('./components/Icon/IconAdd.vue')['default']
    IconChangePassword: typeof import('./components/Icon/IconChangePassword.vue')['default']
    IconCode: typeof import('./components/Icon/IconCode.vue')['default']
    IconContract: typeof import('./components/Icon/IconContract.vue')['default']
    IconDisable: typeof import('./components/Icon/IconDisable.vue')['default']
    IconEdit: typeof import('./components/Icon/IconEdit.vue')['default']
    IconEnable: typeof import('./components/Icon/IconEnable.vue')['default']
    IconEye: typeof import('./components/Icon/IconEye.vue')['default']
    IconFile: typeof import('./components/Icon/IconFile.vue')['default']
    IconFileConfig: typeof import('./components/Icon/IconFileConfig.vue')['default']
    IconFlow: typeof import('./components/Icon/IconFlow.vue')['default']
    IconFolder: typeof import('./components/Icon/IconFolder.vue')['default']
    IconHome: typeof import('./components/Icon/IconHome.vue')['default']
    IconLogin: typeof import('./components/Icon/IconLogin.vue')['default']
    IconLoginBtn: typeof import('./components/Icon/IconLoginBtn.vue')['default']
    IconLogout: typeof import('./components/Icon/IconLogout.vue')['default']
    IconMenu: typeof import('./components/Icon/IconMenu.vue')['default']
    IconProject: typeof import('./components/Icon/IconProject.vue')['default']
    IconSearch: typeof import('./components/Icon/IconSearch.vue')['default']
    IconSetting: typeof import('./components/Icon/IconSetting.vue')['default']
    IconUser: typeof import('./components/Icon/IconUser.vue')['default']
    IconXML: typeof import('./components/Icon/IconXML.vue')['default']
    PersonalDetails: typeof import('./components/Props/PersonalDetails/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
